#gin运行模式：'debug'-'relase'
GinMode: 'debug'
#应用运行的端口
GinPort: '9000'
mysql:
  Username: 'root'
  Password: 'root'
  IpPort: '127.0.0.1:3306'
  Dbname: 'gin'
  Config: 'charset=utf8&parseTime=True&loc=Local'
  MaxIdleConns: 1
  MaxOpenConns: 2